language: elixir
sudo: false

services:
  - postgresql

addons:
  postgresql: "9.4"

elixir:
  - 1.6

otp_release:
  - 20.3
  - 21.0

env:
  global:
    - MIX_ENV=test
  matrix:
    - ECTO2=1
    - ECTO3=1

notifications:
  email: false

script:
  - mix test
  - mix credo
