language: elixir
sudo: false

services:
  - postgresql

addons:
  postgresql: "9.4"

elixir:
  - 1.6

otp_release:
  - 20.3

env:
  global:
    - MIX_ENV=test


matrix:
  include:
    - elixir: '1.7.3'
      otp_release: '21.0'
      env: ECTO3=1
    - elixir: '1.6'
      otp_release: '20.3'

notifications:
  email: false

script:
  - mix test
  - mix credo
